import React, { useMemo, useState } from 'react';
import { AlertTriangle, ChevronDown, HelpCircle, Search, ShieldCheck, Truck, X } from 'lucide-react';
import { Language } from '../types';

type Category = 'all' | 'safety' | 'delivery';
type Item = { id: string; category: Exclude<Category, 'all'>; q: Record<Language, string>; a: Record<Language, string> };

const FAQS: Item[] = [
  { id: 'safe-1', category: 'safety', q: { uz: "Xarid qilish qanchalik xavfsiz va e'lonlar qanday tekshiriladi?", ru: 'Насколько безопасны покупки и как проверяются объявления?', oz: 'Харид қилиш қанчалик хавфсиз ва эълонлар қандай текширилади?' }, a: { uz: "E'lonlar moderatsiyadan o'tadi, ammo hozircha escrow/depozit orqali to'lovni himoyalash xizmati yo'q. Oldindan pul yubormang; tovarni ko'rib, tekshirib, keyin to'lang.", ru: 'Объявления проходят модерацию, но сейчас нет escrow/депозитного сервиса. Не отправляйте предоплату: сначала лично проверьте товар, затем оплачивайте.', oz: 'Эълонлар модерациядан ўтади, аммо ҳозирча escrow/депозит орқали тўловни ҳимоялаш хизмати йўқ. Олдиндан пул юборманг; товарни кўриб, текшириб, кейин тўланг.' } },
  { id: 'safe-2', category: 'safety', q: { uz: 'Firibgarlardan qanday himoyalanish kerak?', ru: 'Как защититься от мошенников?', oz: 'Фирибгарлардан қандай ҳимояланиш керак?' }, a: { uz: "CVV/CVC, SMS/OTP kodlari va karta ma'lumotlarini hech kimga bermang. Shubhali havolalarni ochmang va muhim yozishmalarni Oldisotti ichki chatida olib boring.", ru: 'Никому не сообщайте CVV/CVC, SMS/OTP-коды и данные карты. Не открывайте подозрительные ссылки и ведите важные переговоры во внутреннем чате Oldisotti.', oz: 'CVV/CVC, SMS/OTP кодлари ва карта маълумотларини ҳеч кимга берманг. Шубҳали ҳаволаларни очманг ва муҳим ёзишмаларни Oldisotti ички чатида олиб боринг.' } },
  { id: 'safe-3', category: 'safety', q: { uz: 'Tovar tavsifga mos kelmasa nima qilish kerak?', ru: 'Что делать, если товар не соответствует описанию?', oz: 'Товар тавсифга мос келмаса нима қилиш керак?' }, a: { uz: "Tovarni pul berishdan oldin joyida to'liq tekshiring. Tavsifga mos kelmasa yoki nuqsonli bo'lsa, bitimdan voz keching va pul to'lamang.", ru: 'Проверьте товар на месте до передачи денег. Если он не соответствует описанию или имеет дефект, откажитесь от сделки и не платите.', oz: 'Товарни пул беришдан олдин жойида тўлиқ текширинг. Тавсифга мос келмаса ёки нуқсонли бўлса, битимдан воз кечинг ва пул тўламанг.' } },
  { id: 'delivery-1', category: 'delivery', q: { uz: "Oldisotti ning o'zida yetkazib berish xizmati bormi?", ru: 'Есть ли у Oldisotti собственная доставка?', oz: 'Oldisotti нинг ўзида етказиб бериш хизмати борми?' }, a: { uz: "Hozircha markazlashgan kuryerlik xizmati mavjud emas. Yetkazib berish sotuvchi va xaridor o'rtasida kelishiladi: sotuvchi o'zi yetkazishi yoki xaridor olib ketishi mumkin.", ru: 'Сейчас централизованной курьерской службы нет. Доставка согласовывается между продавцом и покупателем: продавец может доставить сам или доступен самовывоз.', oz: 'Ҳозирча марказлашган курьерлик хизмати мавжуд эмас. Етказиб бериш сотувчи ва харидор ўртасида келишилади: сотувчи ўзи етказиши ёки харидор олиб кетиши мумкин.' } },
  { id: 'delivery-2', category: 'delivery', q: { uz: "Sotuvchi yetkazib berishi qanday kelishiladi?", ru: 'Как согласовать доставку с продавцом?', oz: 'Сотувчи етказиб бериши қандай келишилади?' }, a: { uz: "E'lon sahifasidagi yetkazib berish shartini ko'ring. Narx va usulni ichki chat yoki telefon orqali sotuvchi bilan oldindan kelishib oling.", ru: 'Посмотрите условия доставки в объявлении. Стоимость и способ заранее согласуйте с продавцом через чат или по телефону.', oz: 'Эълон саҳифасидаги етказиб бериш шартини кўринг. Нархи ва усулини ички чат ёки телефон орқали сотувчи билан олдиндан келишиб олинг.' } },
  { id: 'delivery-3', category: 'delivery', q: { uz: "Yetkazib berilganda tovarni qanday qabul qilish kerak?", ru: 'Как принимать товар при доставке?', oz: 'Етказиб берилганда товарни қандай қабул қилиш керак?' }, a: { uz: "To'lovdan oldin mahsulotni ochib, holati, komplektligi va tavsifga mosligini tekshiring. Muammo bo'lsa, qabul qilmang va pul bermang.", ru: 'До оплаты проверьте состояние, комплектность и соответствие описанию. При проблеме не принимайте товар и не передавайте деньги.', oz: 'Тўловдан олдин маҳсулотни очиб, ҳолати, комплектлиги ва тавсифга мослигини текширинг. Муаммо бўлса, қабул қилманг ва пул берманг.' } },
  { id: 'delivery-4', category: 'delivery', q: { uz: "To'lov kimga va qanday amalga oshiriladi?", ru: 'Кому и как производится оплата?', oz: 'Тўлов кимга ва қандай амалга оширилади?' }, a: { uz: "To'lov bevosita sotuvchi va xaridor o'rtasida kelishilgan usulda amalga oshiriladi. Tovarni tekshirmasdan oldindan to'liq to'lov qilish tavsiya etilmaydi.", ru: 'Оплата производится напрямую между продавцом и покупателем согласованным способом. Не рекомендуется оплачивать товар полностью до проверки.', oz: 'Тўлов бевосита сотувчи ва харидор ўртасида келишилган усулда амалга оширилади. Товарни текширмасдан олдиндан тўлиқ тўлов қилиш тавсия этилмайди.' } }
];

const labels = {
  uz: { title: 'Yordam / FAQ', subtitle: "Xavfsizlik va yetkazib berish bo'yicha tez-tez beriladigan savollar", search: "Savol bo'yicha qidiring...", all: 'Barchasi', safety: 'Xavfsizlik', delivery: 'Yetkazib berish', empty: 'Savol topilmadi' },
  ru: { title: 'Помощь / FAQ', subtitle: 'Частые вопросы по безопасности и доставке', search: 'Поиск по вопросам...', all: 'Все', safety: 'Безопасность', delivery: 'Доставка', empty: 'Вопрос не найден' },
  oz: { title: 'Ёрдам / FAQ', subtitle: 'Хавфсизлик ва етказиб бериш бўйича кўп бериладиган саволлар', search: 'Савол бўйича қидиринг...', all: 'Барчаси', safety: 'Хавфсизлик', delivery: 'Етказиб бериш', empty: 'Савол топилмади' }
};

interface Props { isOpen: boolean; lang: Language; onClose: () => void; }

export const HelpFaqModal: React.FC<Props> = ({ isOpen, lang, onClose }) => {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState<Category>('all');
  const [openId, setOpenId] = useState<string | null>('safe-1');
  const text = labels[lang] || labels.uz;
  const filtered = useMemo(() => FAQS.filter((item) => {
    if (category !== 'all' && item.category !== category) return false;
    const q = query.trim().toLowerCase();
    return !q || item.q[lang].toLowerCase().includes(q) || item.a[lang].toLowerCase().includes(q);
  }), [category, lang, query]);
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-3 sm:p-5" role="dialog" aria-modal="true">
    <div className="w-full max-w-2xl max-h-[88vh] overflow-hidden rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 shadow-2xl">
      <div className="flex items-center justify-between gap-3 border-b border-slate-200 dark:border-slate-800 px-4 py-4">
        <div><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600 text-white"><HelpCircle size={17} /></span><h2 className="text-base sm:text-lg font-extrabold text-slate-900 dark:text-white">{text.title}</h2></div><p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">{text.subtitle}</p></div>
        <button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><X size={18} /></button>
      </div>
      <div className="border-b border-slate-200 dark:border-slate-800 px-4 py-3">
        <div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={text.search} className="w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 pl-9 pr-3 py-2 text-xs text-slate-900 dark:text-white outline-none focus:border-indigo-500" /></div>
        <div className="mt-2 flex gap-1.5"><button type="button" onClick={() => setCategory('all')} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-bold ${category === 'all' ? 'bg-indigo-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{text.all}</button><button type="button" onClick={() => setCategory('safety')} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-bold ${category === 'safety' ? 'bg-emerald-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{text.safety}</button><button type="button" onClick={() => setCategory('delivery')} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-bold ${category === 'delivery' ? 'bg-indigo-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{text.delivery}</button></div>
      </div>
      <div className="max-h-[60vh] overflow-y-auto p-3 space-y-2">
        {filtered.length === 0 ? <div className="py-10 text-center text-sm text-slate-500"><AlertTriangle size={22} className="mx-auto mb-2" />{text.empty}</div> : filtered.map((item) => { const open = openId === item.id; return <div key={item.id} className={`overflow-hidden rounded-xl border ${open ? 'border-indigo-200 dark:border-indigo-800' : 'border-slate-200 dark:border-slate-800'}`}><button type="button" onClick={() => setOpenId(open ? null : item.id)} className="flex w-full items-center justify-between gap-3 px-3 py-3 text-left hover:bg-slate-50 dark:hover:bg-slate-800/70"><span className="flex items-center gap-2.5"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-slate-100 dark:bg-slate-800">{item.category === 'safety' ? <ShieldCheck size={16} className="text-emerald-500" /> : <Truck size={16} className="text-indigo-500" />}</span><span className="text-xs sm:text-sm font-bold leading-snug text-slate-800 dark:text-slate-100">{item.q[lang]}</span></span><ChevronDown size={16} className={`shrink-0 text-slate-400 ${open ? 'rotate-180 text-indigo-500' : ''}`} /></button>{open && <div className="border-t border-slate-100 dark:border-slate-800 px-3 pb-3 pt-2 pl-[3.1rem] text-[11px] sm:text-xs leading-relaxed text-slate-600 dark:text-slate-300">{item.a[lang]}</div>}</div>; })}
      </div>
    </div>
  </div>;
};